# Generated by Django 4.1 on 2023-02-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_num_of_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='num_of_comments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_of_documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='num_of_postings',
        ),
    ]
