# Generated by Django 4.1 on 2023-02-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_profile_num_of_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='posistion',
            new_name='position',
        ),
    ]
