# Generated by Django 4.1 on 2023-02-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_rename_posistion_profile_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_engineer",
            field=models.BooleanField(default=False),
        ),
    ]
