# Generated by Django 4.0 on 2023-02-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePost',
            new_name='TicketPost',
        ),
    ]
