# Generated by Django 4.0 on 2023-02-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_articlepost_ticketpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
