# Generated by Django 4.0 on 2023-02-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticketpost_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
